#Comment to check!!!
name: Combined Build Pipeline

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-result:
    name: Build and Push Result Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Result image
        run: |
          docker build -t dexlo/result:latest ./result
          docker push dexlo/result:latest

  build-vote:
    name: Build and Push Vote Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Vote image
        run: |
          docker build -t dexlo/vote:latest ./vote
          docker push dexlo/vote:latest

  build-worker:
    name: Build and Push Worker Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Worker image
        run: |
          docker build -t dexlo/worker:latest ./worker
          docker push dexlo/worker:latest

  sonarqube-analysis:
    name: SonarQube Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11 for SonarQube
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: SonarQube Scanner
        run: |
          sonar-scanner \
          -Dsonar.projectKey=dangdat182_VotingApp \
          -Dsonar.organization=dangdat182 \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
